version: '3.5'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.py
    env_file:
      - postgresenv
    depends_on:
      - database
      
  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - postgresenv
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: